name: Deploy Documentation

on:
  push:
    branches:
<<<<<<< HEAD
      - ruff
=======
      - ruff  # Branche à surveiller
>>>>>>> 3bae0b3 (Résolution des conflits avec corrections des hooks)

jobs:
  deploy:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> 3bae0b3 (Résolution des conflits avec corrections des hooks)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
<<<<<<< HEAD
          python-version: 3.10
=======
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
>>>>>>> 3bae0b3 (Résolution des conflits avec corrections des hooks)

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          publish_dir: docs/build/html
=======
          publish_dir: docs/build/html  # Assurez-vous que ce dossier existe
>>>>>>> 3bae0b3 (Résolution des conflits avec corrections des hooks)
