name: documentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.4"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ghp-import sphinx==7.3.7 sphinx_rtd_theme

    - name: Build HTML
      run: |
        cd docs/
        make html

    - name: Deploy to GitHub Pages (branch: main)
      run: |
        ghp-import -n -p -f docs/build/html -b main
